version: '3.9'
services:
  mermaid:
    image: node:18.16.0-alpine3.18
    stdin_open: true
    tty: true
    working_dir: /mermaid
    # mem_reservation: "10M"
    mem_limit: '8G'
    environment:
      - NODE_OPTIONS=--max_old_space_size=8192
    volumes:
      - ./:/mermaid
      - root_cache:/root/.cache
      - root_local:/root/.local
      - root_local:/root/.npm
    ports:
      - 9000:9000
volumes:
  root_cache:
  root_local:
  root_npm:
