name: Theme Proposal
description: Suggest a new theme to add to Mermaid.js.
labels:
  - "Status: Triage"
  - "Type: Enhancement"

body:
  - type: markdown
    attributes:
      value: |-
        Thank you for suggesting a new Theme for Mermaid.js!
        
        We are always excited for new ideas to make the library more advanced and useful for people.
        Please take your time to fill out the below sections with as much detail as you can.
  - type: textarea
    attributes:
      label: Proposal
      description: A clear and concise description of what theme should be added to Mermaid.js.
      placeholder: Mermaid.js should add ... because ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Colors
      description: |-
        A detailed list of the different colour values to use.
        A list of currently used variable names can be found [here](https://mermaid-js.github.io/mermaid/#/theming?id=theme-variables-reference-table)
      placeholder: |-
        - background: #f4f4f4
        - primaryColor: #fff4dd
        - ...
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to show possible examples of how the theme may look like.
